FDBeye
====

Tools to ease working with eyetracker data. I'm gradually (slowly) migrating stuff from my junkpile of project specific
code into this package. What's here now is focussed on my own workflows involving data from SRR Eyelink systems,
although some stuff may be more generally useful. Functionality is a bit thin. Pitch in and help if you like.

Before you dive into FDBeye, you might want to look at what else is available. See the list below.

Installing FDBeye
-----------------

First you should install <https://github.com/davebraze/FDB1>. Then, install *FDBeye* via devtools::install_github()
```R
install.packages("devtools")    ## if you don't already have it
library(devtools)
install_github("davebraze/FDBeye")
```

License
-------

FDBeye is released under the MIT open source license. See the LICENSE file for details.

Contributing
------------

Contributions are welcome. _IMPORTANT: By submitting a pull request to this project, you agree to release your
contribution to the FDBeye package under the MIT license._

You might want to send me an email before wading in too deep (<davebraze@gmail.com>).

Other Eye Tracking Tools
------------------------

I've kept this list short, limited to tools for post-acquisition summarization and analysis, and where the source code
can be freely downloaded (i.e., you don't have to ask for it, but some of the stuff I've linked to lacks an explicit
Open Source License). I'm sure the list is incomplete. If you know of something that seems like it ought to be included,
let me know. Better yet, fork this repository, make the changes yourself, and send me a pull request.

### *R* packages ###

  * ***edf***: R package for reading SRR *edf files directly. Codebase is both R and C++, and requires SRR's
    edfapi. Source available on SRR's help forum (login via free account required)
    <https://www.sr-support.com/showthread.php?1416-Reading-EDF-files-in-GNU-R>.
  * ***em2***: "package for computing reading time measures for psycholinguistics," i.e. regional reading time
        measures. R package, underlying code mostly C++. Source available on github <https://github.com/cran/em2>.
  * ***emov***: Functions for fixation/saccade detection. On CRAN <https://cran.r-project.org/web/packages/emov/>. Source is
    available on github <https://github.com/schw4b/emov>.
  * ***ETRAN***: Fixation detection, plotting. Available from this web site <https://sites.google.com/site/azhegallo/>, and
    written up in the journal _Perception_ here:
    <http://pec.sagepub.com/content/early/2015/08/14/0301006615594944.full>.
  * ***eyelinker***: Tool for converting SRR *ASC files to data.frames. Available on github
    <https://github.com/dahtah/eyelinker>. Not clearly open source; no license statement at all.
  * ***eyetracking***: Compute pixel-to-pixel and eye-to-screen distances. On CRAN
    <https://cran.r-project.org/web/packages/eyetracking/>.
  * ***eyetrackingR***: Package oriented toward post-acquisition workflow, mostly for 'visual world' style studies. On
    CRAN <https://cran.r-project.org/web/packages/eyetrackingR/>. It also has its own web site here:
    <http://www.eyetracking-r.com/>. The source is available on github <https://github.com/jwdink/eyetrackingR>.
  * ***fix_align.R***: automatically adjusts y coordinate of fixations in multi-line reading paradigm so that each falls
    on a specific line of text. As written, code is specific to SRR systems (requires SRR ASC files as input). At UMass
    <http://www.psych.umass.edu/PACLab/resources/>. Described in *Behav Res*:
    <http://people.umass.edu/eyelab/CohenBRM.pdf>. Source file (v0p92) includes the notice "(c) 2012, University of
    Massachussetts, All rights reserved". The latter bit seems to entail that the code may not be modified,
    redistributed, or even used without first obtaining explicit permission from UMass. Odd.
  * ***gazepath***: Functions for fixation/saccade detection. On CRAN
    <https://cran.r-project.org/web/packages/gazepath/>. Source on github <https://github.com/cran/gazepath>.
  * ***saccades***: Functions for fixation/saccade detection. On CRAN
    <https://cran.r-project.org/web/packages/saccades/>. Source on github
    <https://github.com/tmalsburg/saccades>. author's website <http://pages.ucsd.edu/~tvondermalsburg/saccades/>.
  * ***ScaSim***: author's website <http://pages.ucsd.edu/~tvondermalsburg/scasim/>. Scan path similarity analysis. Last
    updated 2010.

### *Python* packages ###

  * ***cili***: on github <https://github.com/beOn/cili>. Reduce overhead in working with SRR Eyelink data. Extracts
    events from SRR ASC files and provides as pandas DataFrames.
  * ***DynAOI***: on launchpad <https://launchpad.net/dynaoi>. Described in *Behav Res*
    <https://www.iwm-tuebingen.de/cybermedia/dynaoi/PapenmeierHuffBRM.pdf>. Analysis of EM in relation to
    moving objects. Python codebase, relies on Blender for some functions. Last update in 2011.
  * ***eventdetect***: on github <https://github.com/gian/eventdetect>. Repository of event detection algorithms. Python
    codebase. Last update in 2015. Development seems sluggish.
  * ***EyeSimplify***: web site at <http://www.cl.uni-heidelberg.de/seminare/studpro06/eyesimplify/>. Convenience wrapper
    with automation for UMass tools (*EyeDoctor* etc.). Possibly superceded by *RoboDoc.py*. Python codebase. Last
    update in 2007.
  * ***iMap***: author's website <http://perso.unifr.ch/roberto.caldara/index.php?page=3>. Fixation pattern
    analysis and visualization. Described in a couple of journal articles: *Behav Res*
    <http://perso.unifr.ch/roberto.caldara/pdfs/caldara_11.pdf> and *J of Vision*
    <http://jov.arvojournals.org/article.aspx?articleid=2433901>. Matlab toolbox. Seems current.
  * ***ocupy***: on github <https://github.com/nwilming/ocupy>. Python codebase. "tools for analyzing eye-tracking
    data". last update in 2015, sluggish development.
  * ***pyarbus***: on github <https://github.com/ivanov/pyarbus>. Python codebase. Major functionality seems to be
    for extracting sample and message info from SRR *asc files. Last update in 2013.
  * ***pyeparse***: on github <https://github.com/pyeparse/pyeparse>. Python codebase. "analyzing eye tracking data from
    cogntive sciences experiments," SRR eyelink trackers. Last update in 2015. Seems active.
  * ***PyGaze***: on github <https://github.com/esdalmaijer/PyGaze>. Python codebase. Focussed on data collection
    "programming of eyetracking experiments". Web site at <http://www.pygaze.org/>. Also see BRM paper
    <http://link.springer.com/article/10.3758%2Fs13428-013-0422-2>. Actively developed.
  * ***PyGazeAnalyser***: Post-acquisition processing tools associated with PyGaze. On GitHub at
    <https://github.com/esdalmaijer/PyGazeAnalyser>. Parses SRR ASC files and SensoMotoric IDF ASCII files. Plots
    heatmaps, scanpaths, fixation locations.
  * ***Samara***: on github <https://github.com/m-macaskill/Samara>. Python codebase. Saccade analysis, SMI iView
    trackers. Last update in 2013.

### *Matlab* toolkits ###

  * ***EALab***: web site <https://ealab-matlabtoolbox.rhcloud.com/>.  Described in *Neuroinform*
    <http://dx.doi.org/10.1007/s12021-015-9275-4>. Matlab toolbox. Classification and extraction of eye
    activity/events. Seems current.
  * ***ETML***: on github <https://github.com/jwdink/ETML>. Matlab codebase. "Framework for running eyetracking experiments
    in MATLAB," with SRR eyelink systems. Seems active.
  * ***EyeMMV***: on github <https://github.com/krasvas/EyeMMV>. Matlab toolbox. post-collection eye movement
    analysis. Last update in 2014. Described in J. of *Eye Movement Research* <http://www.jemr.org/online/7/1/1>.
  * ***ScanMatch***: web page <http://seis.bris.ac.uk/~psidg/ScanMatch/>. Described in *Behav Res*
    <http://seis.bris.ac.uk/~psidg/ScanMatch/CMTG2010.pdf>. Scan path analysis. Matlab toolbox. Last update 2009.
  * ***calib_adjust_code*** web page at <http://langcog.stanford.edu/materials/calib.html>. Method for offline
    calibration adjustment of Tobii eyetrackers, specifically geared toward work with infants. Additional description in
    the journal _Infancy_ <http://langcog.stanford.edu/papers/FVS-infancy2012.pdf>.

### Other languages ###

  * ***CARPE***: on google code <https://code.google.com/archive/p/dynamic-images-and-eye-movements/>. visualization and
    collection of gaze patterns over dynamic images. Project home page on wordpress
    <https://thediemproject.wordpress.com/>. Looks fairly polished, but no recent development (since 2010).
  * ***EyeMap***: on sourceforge <http:/openeyemap.sourceforge.net/>. Java codebase. Last update in 2012.
  * ***EyePatterns***: on sourceforge <http://sourceforge.net/projects/eyepatterns/>. Looks for patterns/similarities in
    fixation sequences. Java codebase. Last update in 2013.
  * ***eyetracker***: on github <https://github.com/stefan-k/eyetracker>. C++ codebase. Last update in 2012.
  * ***EyeTrack***, ***EyeDoctor***, ***EyeDry***, ***RoboDoc.py***: Designed for reading studies and for use with SRR
    ET systems. Available from Staub lab at UMass <https://blogs.umass.edu/eyelab/software/>. C++ codebase, some
    Python. Seems current.
  * ***OGAMA***: on codeplex <http://www.ogama.net/>. Data collection, fixation detection, scanpath analysis, and
    heatmaps. Supports Tobii and Alea Tech ET systems only. Also does mouse tracking. C# codebase. Seems current.
