---
title: "Text Canvases part 1: SRR Experiment Builder"
author: "Dave Braze"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SRR Experiment Builder Text Canvases}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

In our terminology, a *text canvas* is a bitmap image of text,
formatted as it might appear on a printed page. A *text canvas* is the
kind of stimulus used in an experiment where participants' eye
movements are recorded while they read from a computer monitor.

In our lab, we typically generate *text canvas* stimuli for an
experiment offline and then provide those to whatever experiment
control software will be used for data acquisition. For us, most often
that's SRR _Experiment Builder_. This offline approach to stimulus
construction gives us complete control over the appearance of the
visual stimuli, and lets us use pixel-identical stimuli on different
computers, or with different experiment control software (e.g.,
_Experiment Builder_, _E-Prime_, _Presentation_).

An offline approach also let's us use our own tools for creating and
modifying regions of interest (aka interest areas). These ROIs are
used for the purpose of summarizing gaze behavior over a text. The
most natural default for regions of interest is that they correspond
to the individual words in the text. But it is often the case that
mapping gaze data onto multi-word regions that correspond to larger
syntactic or semantic constituents is useful. The tools provided by,
e.g., _Experiment Builder_ for redefining ROIs are tedious to use and
not very intuitive. Ours are better.

However, _Experiment Builder_ (and presumably other experiment control
software) can also create *text canvases* internally, from plain text
(ascii or unicode) provided to them. _Experiment Builder_ will do so
only if the IMAGE\_RESOURCE used to display the text in _EB_ project
has its _Prebuild to Image_ property checked. In that case, the text
canvases will be saved to the `/runtime/images/` subfolder within the
project as PNG bitmaps. Unfortunately, they are give rather cryptic
file names, like `-6812265288292522003.png`.

You can determine which of these PNG files was used in which trial, by
checking a set of _EB_ generated text files located in the
`/runtime/dataviewer/[EDF filename]/graphics/` subfolder of the
project. These files will have a vcl extension and the filenames
include numbers that correspond to trial numbers (e.g., `VC\_1.vcl`,
`VC\_2.vcl`). The content of a file will look something like this:

```
0 IMGLOAD TOP_LEFT  ../../runtime/images/-6812265288292522003.png 0 0 1024 768
```

The filename of the *text canvas* used for the particular trial is
clearly specified. An simple R script to extract this information will
not be too hard to construct. (Of course, you could also copy the
information out by hand....)

See the email appended below for details on how to extract this
information from an _Experiment Builder_ project using SRR _Data
Viewer_.

```
-------- Forwarded Message --------
Subject: 	Re: Data Viewer
Date: 	Thu, 21 Apr 2016 11:15:31 -0400
From: 	Marcus Johnson <marcus@sr-research.com>
To: 	Jenna Duclos <duclos@haskins.yale.edu>
```


Hi Jenna,

First, I should mention are trying to get images from the runtime
folder then there is likely an easier way to do what you are trying to
do. :)

Perhaps if you could describe why you might need to get the images
from the runtime folder I might be able to offer an easier solution to
what you are trying to do.

The images in the runtime folder are not really meant to be
accessed/used by the end user.  Their naming comes from a kind of
key:response algorithm that automatically generates the name based on
the filename.  It's meant to kind of encrypt the information, so there
is no pattern that can give you information in the filename.

You can check some text files in the
`/runtime/dataviewer/[EDF filename]/graphics/` folder of the project to
find out the image filename that was used on each trial.  Each text
file (which has a VCL extension) will have a command that will point
to the image file and where it was presented on the screen.  E.g.,:

```
0 IMGLOAD TOP_LEFT  ../../runtime/images/-6812265288292522003.png 0 0 1024 768
```

That will tell you which image file was used on each trial.  The text
file names will reflect the randomized order of the images if they
were indeed randomized.

Alternatively, from Data Viewer you can do the following to generate a
text file that has these types of messages in it:

1. First go to Edit -> Preferences -> Data Filters and make sure that
"Include Display Command Messages" is checked.
1. Generate a Message Report (Analysis -> Reports -> Message Report).
Include the variables RECORDING\_SESSION\_LABEL and TRIAL\_INDEX to
identify the trial number.  Also include the variable
CURRENT\_MSG\_TEXT -- this will contain those types of messages
(IMGLOAD messages) that point to the image file names.

Note, if an IMAGE\_RESOURCE in a project did not have its Prebuild to
Image property checked then it will not create these types of files in
the runtime folder for the image files that this IMAGE\_RESOURCE uses.
If this is the case, the project will store a copy of the original
image file -- you will be able to find the original image files in the
/library/images folder of the project.

That being said, for most projects, the image filename to be used on
each trial comes from a Data Source column associated with a sequence
that is handling the trial looping of the project.  If you select all
of your Data Source columns and VARIABLE nodes as EyeLink DV Variables
at the top-most level of the Structure Panel then it will make it so
that their values get written to the EyeLink data file every time the
system stops recording (i.e., at the end of each trial).  Note, these
EyeLink DV Variables become Trial Variables in Data Viewer that can be
added as columns to any of the reports you create in Data Viewer
(Analysis -> Reports).  You can check if your EDF files have these
values by going to Analysis -> Trial Variable Value Editor in Data
Viewer.  This will tell you the original image filename that was used.

Also, if you didn't include the Data Source column name as an EyeLink
DV Variable then you will still have a record of the value used on
each trial (in the randomized order).  In each subject's results
folder there will be a .dat file.  This is a tab-delimited text file
that has the values of the Data Source column values that were used on
each trial.  So, you can recover the name of the original image that
was used on each trial in that way.

Again, if you can send me a copy of the project and a description of
what you are trying to do then I might be able to offer an easier
solution than digging through the runtime folder (no promises, but
I'll do my best).

Thanks,

Marcus
