## Let's refer to a bitmap image of text used for display of text
## stimuli as a "text canvas".

##' @title Sweep text canvases horizontally to estimate line locations.
##'
##' @TODO Work on getting top and bottom margin for each line, as well
##'     as estimated baseline.
##' @TODO Figure out where to find auto generated trial-wise text
##'     canvases from SRR EB demo for single sentence reading. Then
##'     point to that location in this help file.
##' @param canvas A N dimensional matrix (product of png::readPNG())
##'     corresponding to bitmap image.
##' @return A data frame containing 1 row for each line of text in the
##'     canvas, and the following columns:
##'
##' \enumerate{
##'     \item line: Integer indicating line number, counting from the top of the canvas.
##'     \item top: Integer indicating upper extent of line in pixels.
##'     \item baseline: Integer indicating location of line's baseline (estimated) in pixels.
##'     \item bottom: Integer indicating lower extent of line in pixels.
##' }
##'
getLines <- function(canvas){}


##' @title Sweep each line of text in a text cavas to estimate
##'     character locations.
##'
##' @param canvas A N dimensional matrix (product of png::readPNG())
##'     corresponding to bitmap image.
##' @param lines Data.frame generated by applying guessLines() to
##'     canvas.
##' @return A data frame containing 1 row for each character in each
##'     line of canvas, and the following columns:
##'
##' \enumerate{
##'     \item line: Integer indicating line number, counting from the top of the canvas.
##'     \item char: Integer indicating the character number, counting from the left most.
##'     \item left: Integer indicating left-most extent of character in pixels.
##'     \item right: Integer indicating right-most extent of character in pixels.
##' }
##'
getChars <- function(canvas, lines){}

